### ISSUE TITLE
Pre presentation links

### ISSUE THREAD

**Issue by kkashTLG** [Weijun124/SDE-JS#11]
- [x]  [User Story Doc Link Rev 0](https://lucid.app/lucidchart/cf8acfde-062e-43f5-a717-eda329445d63/edit?invitationId=inv_f7dc5de0-e926-4edf-8b4b-58aa05df1afb&page=0_0#)
- [x]  [User Story Doc Link Rev 1](https://lucid.app/lucidspark/bd17cdf2-869a-449c-b71c-dde129276d7f/edit?beaconFlowId=FDD3E1158CF351BF&invitationId=inv_fc0c3aba-8869-4057-9d42-1b6ec814d154#)
- [x] [ Github Project Link](https://github.com/users/Weijun124/projects/5)
- [x] [Front-End LiveLink (Github Page Link)](https://weijun124.github.io/SDE-JS/)
- [x] [Front-End Github Repo Link](https://github.com/Weijun124/SDE-JS)

**Comment by nabindhakall** [comment]
![Image](https://user-images.githubusercontent.com/109391456/189941187-acdd43ac-1de2-4013-97ab-08d1f448eaaf.PNG)
